### ISSUE TITLE
cannot parse wiki

### ISSUE THREAD

**Issue by karussell** [westnordost/osm-legal-default-speeds#13]
I'm relative sure I did something incorrectly. Maybe when I added Indonesia to the wiki or are there certain requirements for the python version?

I followed the readme and tried to create the json with:

python parser/main.py

but I got:

```

Traceback (most recent call last):
  File "/home/user/code/osm-legal-default-speeds/parser/parsers/parse_utils.py", line 126, in parse_speed_table
    parsed_speeds = speed_parse_func(speeds)
  File "/home/user/code/osm-legal-default-speeds/parser/parsers/osm_restrictions.py", line 92, in parse_speeds
    parse_tree = parser.parse(s)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark/lark.py", line 581, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark/parser_frontends.py", line 106, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark/parsers/earley.py", line 297, in parse
    to_scan = self._parse(lexer, columns, to_scan, start_symbol)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark/parsers/xearley.py", line 144, in _parse
    to_scan = scan(i, to_scan)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark/parsers/xearley.py", line 118, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan},
lark.exceptions.UnexpectedCharacters: No terminal matches 'a' in the current parser context, at line 1 col 30

55 mph (articulated),55 mph (agricultural)
                             ^
Expected one of: 
	* NUMBER
	* EVENT
	* WEIGHT_QUALIFIER
	* MONTH
	* LPAR
	* WEIGHT
	* WEEKDAY
	* TIME
	* RESTRICTION_CONDITIONAL


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parser/main.py", line 31, in <module>
    result = parse_speed_table(speed_table, parse_speeds)
  File "/home/user/code/osm-legal-default-speeds/parser/parsers/parse_utils.py", line 129, in parse_speed_table
    warnings.append(f'{country_and_subdivision_name}: Unable to parse \'{vehicle_type}\' for \'{road_type}\'')
NameError: name 'country_and_subdivision_name' is not defined
```

**Comment by westnordost** [comment]
The parser simply doesn't know "agricultural". Someone added that to the wiki page.

**Comment by westnordost** [comment]
I think it is an easy fix to add that to the understood values. I could give you push access too, this could make it easier to maintain in the future.
